# -*- coding: utf-8 -*-
"""python_matplotlib-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2CMvdD8RGdMdWdtJUyZZtNUZpLN6VFm

## Visualização de dados com Python + Matplotlib

O matplotlib é uma das bibliotecas de Python utilizadas para criar gráficos estáticos, animados e interativos.
"""

# Instalação (python >= 3.0)
# Utilizando o pip:
!pip install matplotlib

# Utilizando o anaconda:
#conda create -n <nome-do-ambiente-virtual>
#conda install -c conda-forge::matplotlib

# Utilizando o anaconda já criando o ambiente virtual com bibliotecas específicas:
# conda create -n <nome-do-ambiente-virtual> python=3.x.x #cria ambiente com a versão 3.x.x do python
# conda create -n <nome-do-ambiente-virtual> python numpy matplotlib # Cria o ambiente com python, numpy, matplotlib, ...

"""### Visualização de dados 101:"""

# Criando um gráfico no matplotlib:
import matplotlib.pyplot as plt


dados_x = [1, 3, 5, 7, 9]
dados_y = [1, 9, 25, 49, 81]

plt.plot(dados_x, dados_y)
plt.show()

"""### Customizando o gráfico:
Vamos adicionar algumas customizações ao nosso gráfico como mudar a cor e estilo da linha, adicionar marcadores, legendas nos eixos e rotular os dados.
"""

plt.plot(dados_x,
         dados_y,
         marker='*',
         color='green',
         linewidth=1.5,
         linestyle='--',
         label=r'f(x) = $x^{2}$')

plt.legend()
plt.xlabel("x", fontsize=12)
plt.ylabel("f(x)", fontsize=12)

plt.savefig('grafico.png', dpi=300)
plt.show()

"""### Gerando dados mais interessantes para a visualização

Agora, vamos utilzar o `numpy` para gerar alguns dados e produzir graficos mais interessantes.
"""



plt.style.use('default')
import numpy  as np

def f(x):
  return x**3

dominio = np.linspace(0, 1, 100)

plt.plot(dominio,
         f(dominio),
         color='blue',
         ls='--',
         lw=1.25,
         label=r'f(x) = $\omega$')

plt.legend(frameon=False, loc="upper left")
plt.title(r'f(x) = $x^{3}$', fontsize=15)
plt.xlabel("x", fontsize=12)
plt.ylabel("f(x)", fontsize=12)

plt.show()

"""## Múltiplos gráficos"""

fig, axs = plt.subplots(1,2)

dominio = np.linspace(0, np.pi, 100)

axs[0].plot(dominio, np.sin(dominio), color='k')
axs[0].set_xlabel("x", fontsize=12)
axs[0].set_ylabel("f(x)", fontsize=12)

axs[1].plot(dominio, np.cos(dominio), color='k')
axs[1].set_xlabel("x", fontsize=12)
axs[1].set_ylabel("f(x)", fontsize=12)

plt.tight_layout()
plt.show()

"""### Outros tipos de gráficos:"""

# Mudar o estilo padrao:
plt.style.use('ggplot')

fisica_comp = {
    2018: {
        "tot_alunos": 23,
        "Fisica": int(0.6*23),
        "Matematica": int(0.1*23),
        "Engenharias": int(0.3*23),
    },
    2019: {
        "tot_alunos": 18,
        "Fisica": int(0.4*18),
        "Matematica": int(0.1*18),
        "Engenharias": int(0.5*18),
    },
    2020: {
        "tot_alunos": 25,
        "Fisica": int(0.7*25),
        "Matematica": int(0.15*25),
        "Engenharias": int(0.15*25),
    },
    2021: {
        "tot_alunos": 22,
        "Fisica": int(0.3*22),
        "Matematica": int(0.15*22),
        "Engenharias": int(0.55*22),
    },
    2022: {
        "tot_alunos": 20,
        "Fisica": int(0.8*20),
        "Matematica": int(0.05*20),
        "Engenharias": int(0.15*20),
    },
    2023: {
        "tot_alunos": 15,
        "Fisica": int(0.6*15),
        "Matematica": int(0.1*15),
        "Engenharias": int(0.3*15),
    },
    2023: {
        "tot_alunos": 4,
        "Fisica": int(1*4),
        "Matematica": int(0.0*4),
        "Engenharias": int(0.0*4),
    }
}

fig,  axs = plt.subplots(2, 2, figsize=(9,6))

periodo = list(fisica_comp.keys())

# 1 - Número de alunos ao longo dos anos:
no_alunos  = []

for x in periodo:
  no_alunos.append(fisica_comp[x]["tot_alunos"])

axs[0,0].bar(periodo, no_alunos, color='green')
axs[0,0].set_xlabel("Ano", fontsize=10)
axs[0,0].set_ylabel("Número de alunos", fontsize=10)

# 2 - Número de alunos dos diferentes cursos ao longo dos anos:
no_alunos_fis = []
no_alunos_mat = []
no_alunos_eng = []

for x in periodo:
  no_alunos_fis.append(fisica_comp[x]["Fisica"])
  no_alunos_mat.append(fisica_comp[x]["Matematica"])
  no_alunos_eng.append(fisica_comp[x]["Engenharias"])

axs[0,1].plot(periodo, no_alunos_fis,
                 color='blue', marker='o',
                 label='Física')

axs[0,1].plot(periodo, no_alunos_mat,
                 color='red', marker='*',
                 label='Matemática')

axs[0,1].plot(periodo, no_alunos_eng,
                 color='k', marker=6,
                 label='Engenharias')


axs[0,1].set_xlabel("Ano", fontsize=10)
axs[0,1].set_ylabel("Número de alunos", fontsize=10)

axs[0,1].set_ylim([0,25])
axs[0,1].legend(ncol=3, fontsize=8)

# 3 - Distribuição de alunos em 2020:
no_alunos_2020 = fisica_comp[2020]["tot_alunos"]
no_alunos_2020_fis = fisica_comp[2020]["Fisica"]
no_alunos_2020_mat = fisica_comp[2020]["Matematica"]
no_alunos_2020_eng = fisica_comp[2020]["Engenharias"]

percent = [no_alunos_2020_fis/no_alunos_2020,
           no_alunos_2020_mat/no_alunos_2020,
           no_alunos_2020_eng/no_alunos_2020]

axs[1,0].set_title("Distribuição dos alunos em 2020", fontsize=10)
axs[1,0].pie(percent,
             labels=["Física", "Matemática", "Engenharias"])


# 4 - Distribuição dos alunos ao longo dos anos:

fisica = [fisica_comp[x]["Fisica"] for x in periodo]
matematica = [fisica_comp[x]["Matematica"] for x in periodo]
engenharias = [fisica_comp[x]["Engenharias"]for x in periodo]

dados = [fisica, matematica, engenharias]
axs[1,1].boxplot(dados, labels=["Física", "Matemática", "Engenharias"])
axs[1,1].set_title("Alunos em cada disciplina ao longo dos anos", fontsize=10)
axs[1,1].set_ylabel("Número de Alunos")

plt.tight_layout()
plt.savefig("graficos.png", dpi=300)

"""## Histogramas"""

plt.style.use('default')
dados = np.loadtxt("student_grades.txt")

normal_dist = np.random.normal(scale=3, size=100000)
normal_data = np.round(normal_dist)

range_bins = np.arange(start=min(normal_data), stop = max(normal_data) + 1)

fig, axs = plt.subplots(1,2, figsize=(10,4))

axs[0].hist(dados, 10)
axs[0].set_xlim([0,10])

axs[0].set_xlabel("Notas")
axs[0].set_ylabel("Frequencias")

axs[1].hist(normal_data, bins=range_bins,
            fill=False)

plt.savefig("hist_1.png", dpi=300)
plt.show()

"""Diferentes estilos:"""

fig, axs = plt.subplots(2,2, figsize=(10,4))

colors = ['#2ca25f', '#8856a7', '#fdbb84', '#43a2ca']
hatchs = ['//', '++', 'xx', '**']
k = 0

for i in range (0, 2):
  for j in range(0, 2):
    axs[i,j].hist(normal_data, bins=range_bins,
                  color=colors[k],
                  fill=True,
                  hatch=hatchs[k])
    axs[i,j].set_xticks([])
    axs[i,j].set_yticks([])

    k += 1

plt.tight_layout()